[project]
name = "cli-based-game"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "SaidDev", email = "frontendcareerjourney@gmail.com" }
    ]
requires-python = ">=3.12"
dependencies = [
    "pyyaml>=6.0.3",
]

[project.scripts]
cli-based-game = "cli_based_game:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
